playerms:
  msg: Welcome to Player Microservice default configuration
  build.version: 0.1
  mailDetails:
    hostname: dmmarques
    port: 8092
    from: dmmarques@fullstack.com
    subject: Player MS Config default config

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: player
      host: localhost
      port: 27017

server:
  port: 8081
