server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/dmmarques/spgestConfigServer.git"
          clone-on-start: true
          default-label: master
